export interface Session {
  cinema: string;
  day: string;
  time: string;
  title: string;
  year: number;
  country: string;
  duration: number;
  director: string;
  mostra: string;
  poster: string;
}

export const CINEMAS = [
  "BIBLIOTECA ROBERTO SANTOS",
  "BIBLIOTECINE",
  "CASA DE FRANCISCA",
  "CCBB",
  "CCSP",
  "CFC CIDADE TIRADENTES",
  "CINE BELAS ARTES",
  "CINE BIJOU",
  "CINECLUBE BA",
  "CINECLUBE CINCO",
  "CINECLUBE DO JAPONÊS",
  "CINECLUBE FGV",
  "CINECLUBE MARIETA",
  "CINE JOIA",
  "CINE MATILHA",
  "CINE OLIDO",
  "CINE SEGALL",
  "CINESESC",
  "CINE-TEATRO DENOY DE OLIVEIRA",
  "CINEMATECA BRASILEIRA",
  "CINUSP",
  "CINUSP MARIA ANTÔNIA",
  "ESPAÇO PETROBRAS DE CINEMA",
  "INSTITUTO MOREIRA SALLES",
  "MIS",
  "NÁSTIENKA CINECLUBE RUSSO",
  "NASTIENKA CINECLUBE",
  "PATUÁ DISCOS",
  "SESC 24 DE MAIO",
  "SESC AVENIDA PAULISTA",
  "SESC BELENZINHO",
  "SESC CAMPO LIMPO",
  "SESC CONSOLAÇÃO",
  "SESC INTERLAGOS",
  "SESC IPIRANGA",
  "SESC PINHEIROS",
  "SESC POMPEIA",
  "SESC SANTANA",
  "SESC SANTO AMARO",
  "SESC VILA MARIANA",
  "SOBERANO",
];

export const DAYS = [
  "SEGUNDA-FEIRA",
  "TERÇA-FEIRA",
  "QUARTA-FEIRA",
  "QUINTA-FEIRA",
  "SEXTA-FEIRA",
  "SÁBADO",
  "DOMINGO",
];
